- name: Delete old virtual machines
  shell: |
    if [ -f /vm/images/{{host}}.qcow2 ]; then
              virsh destroy {{host}}
              virsh undefine {{host}}
              rm -f /vm/images/{{host}}.qcow2
              rm -fr /vm/conf/{{host}}
    fi
  with_inventory_hostnames:
    - cluster-managers
    - cluster-balancers
    - cluster-storages
    - cluster-workers
  loop_control:
    loop_var: host

